### ISSUE TITLE
[Backend] desarrollar temas de incidencias

### ISSUE THREAD

**Issue by aolite** [UdLJointProject/CRM#32]
Desarrollar un formulario para la definición y envío de incidencias. Esta tarea se centrará en: 
- [ ]  Desarrollo de los servicios para enviar la incidencia y almacenamiento en la BBDD. 
- [ ]  Desarrollo de la pantalla para la definición de dicha incidencia.

**Comment by aexposito6** [comment]
Funcionalidad implementada
