### ISSUE TITLE
Revision version paralela del CRM

### ISSUE THREAD

**Issue by aolite** [UdLJointProject/CRM#43]

**Comment by aolite** [comment]
Buenas grupo, 

He estado revisando la version "paralela" que me comentasteis ayer. Os adjunto una captura de pantalla: 

<img width="1280" alt="crm_group2" src="https://cloud.githubusercontent.com/assets/4601466/26274794/66ff2240-3d52-11e7-8e30-dc4e80838162.png">

Desde mi punto de vista, esta versión aparentemente carece de las funcionalidades que me mostrasteis ayer en la "otra" versión. Debéis tomar una decision teniendo en cuenta que la semana que viene es el ultimo deadline y la aplicación debe estar terminada. Mi recomendación tal y como os comenté ayer es que sigáis con la versión que me mostraseis ayer añadiéndole las funcionalidades que os faltan por hacer. 

También y como apunte, esto es un trabajo en grupo donde todo el mundo debe colaborar tanto en el desarrollo, análisis de requerimientos y gestión de la calidad. Por ello, las individualidades (por lo menos en lo que yo valoro) serán penalizarles ya que el objetivo es gestión y trabajo grupal. 

Aun y todo, sois vosotros los que debéis llegar a una decisión grupal. Por eso, cuando lleguéis a dicha conclusión, por favor comunicármela por este canal. En todo caso, solo se evaluará una única versión por cada grupo (hasta que no me digan lo contrario).

**Comment by deinok** [comment]
@aolite Hemos decidido juntar las dos partes.
